M48
; DRILL file {KiCad (6.0.1)} date Tue Feb 22 10:12:27 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-02-22T10:12:27+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.1)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X1.83Y-1.41
X1.83Y-10.37
X6.64Y-6.5498
X10.79Y-1.41
X10.81Y-10.38
T0
M30
